# Generated by Django 5.2.10 on 2026-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='slug',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
