# Generated by Django 5.2.13 on 2026-05-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_gallery_category'),
        ('backend_app', '0002_remove_specialist_email_remove_specialist_phone_and_more'),
    ]

    operations = [
    ]
