# Generated by Django 5.2.13 on 2026-05-04 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_merge_20260504_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
