# Generated by Django 4.2.25 on 2026-05-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_packages_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
    ]
