# Generated by Django 3.2 on 2026-05-23 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('author_name', models.CharField(default='Dr. Naveen Kumar', max_length=100)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
