# Generated by Django 5.2.13 on 2026-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='heading',
        ),
        migrations.AddField(
            model_name='packages',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
