# Generated by Django 5.2.13 on 2026-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_packages_description_remove_packages_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='main_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
