# Generated by Django - manually edited to handle existing rows safely

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Packages = apps.get_model('backend_app', 'Packages')
    seen = {}
    for pkg in Packages.objects.all():
        base = slugify(pkg.title) or f'package-{pkg.pk}'
        slug = base
        counter = 1
        while slug in seen:
            slug = f'{base}-{counter}'
            counter += 1
        seen[slug] = True
        pkg.slug = slug
        pkg.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_packages_main_description'),
    ]

    operations = [
        # Step 1: Add slug as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='packages',
            name='slug',
            field=models.SlugField(max_length=200, blank=True, null=True),
        ),
        # Step 2: Populate slugs from existing titles
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Now make it unique and non-nullable
        migrations.AlterField(
            model_name='packages',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, blank=True),
        ),
    ]
