name: Test SSH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 88.222.215.246
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            hostname
            whoami
